apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticolops-api
  labels:
    app: ticolops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticolops-api
  template:
    metadata:
      labels:
        app: ticolops-api
    spec:
      containers:
        - name: ticolops-api
          image: ghcr.io/${{ github.repository }}:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ticolops-secrets
                  key: database_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ticolops-secrets
                  key: redis_url
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ticolops-api
spec:
  selector:
    app: ticolops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ticolops-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ticolops-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
