name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Kubernetes
        if: always()
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "Applying k8s manifests"
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/ingress.yaml
